config/routes.rb
Rails.application.routes.draw do
  resources :regs
  get 'register' => 'regs#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reg.rb
class Reg < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/regs_controller.rb
class RegsController < ApplicationController
  before_action :set_reg, only: [:show, :edit, :update, :destroy]

  # GET /regs
  # GET /regs.json
  def index
    @regs = Reg.all
  end

  # GET /regs/1
  # GET /regs/1.json
  def show
  end

  # GET /regs/new
  def new
    @reg = Reg.new
  end

  # GET /regs/1/edit
  def edit
  end

  # POST /regs
  # POST /regs.json
  def create
    @reg = Reg.new(reg_params)

    respond_to do |format|
      if @reg.save
        format.html { redirect_to @reg, notice: 'Reg was successfully created.' }
        format.json { render :show, status: :created, location: @reg }
      else
        format.html { render :new }
        format.json { render json: @reg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regs/1
  # PATCH/PUT /regs/1.json
  def update
    respond_to do |format|
      if @reg.update(reg_params)
        format.html { redirect_to @reg, notice: 'Reg was successfully updated.' }
        format.json { render :show, status: :ok, location: @reg }
      else
        format.html { render :edit }
        format.json { render json: @reg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regs/1
  # DELETE /regs/1.json
  def destroy
    @reg.destroy
    respond_to do |format|
      format.html { redirect_to regs_url, notice: 'Reg was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reg
      @reg = Reg.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reg_params
      params.require(:reg).permit(:username, :password, :dateofbirth, :email, :telephone, :address, :city, :postcode)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/regs_helper.rb
module RegsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Registration</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/regs/_form.html.erb
<%= form_with(model: reg, local: true) do |form| %>
  <% if reg.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reg.errors.count, "error") %> prohibited this reg from being saved:</h2>

      <ul>
      <% reg.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username, id: :reg_username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :reg_password %>
  </div>

  <div class="field">
    <%= form.label :dateofbirth %>
    <%= form.date_select :dateofbirth, id: :reg_dateofbirth %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :reg_email %>
  </div>

  <div class="field">
    <%= form.label :telephone %>
    <%= form.number_field :telephone, id: :reg_telephone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :reg_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :reg_city %>
  </div>

  <div class="field">
    <%= form.label :postcode %>
    <%= form.number_field :postcode, id: :reg_postcode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/regs/edit.html.erb
<h1>Editing Reg</h1>

<%= render 'form', reg: @reg %>

<%= link_to 'Show', @reg %> |
<%= link_to 'Back', regs_path %>

app/views/regs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regs</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Dateofbirth</th>
      <th>Email</th>
      <th>Telephone</th>
      <th>Address</th>
      <th>City</th>
      <th>Postcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regs.each do |reg| %>
      <tr>
        <td><%= reg.username %></td>
        <td><%= reg.password %></td>
        <td><%= reg.dateofbirth %></td>
        <td><%= reg.email %></td>
        <td><%= reg.telephone %></td>
        <td><%= reg.address %></td>
        <td><%= reg.city %></td>
        <td><%= reg.postcode %></td>
        <td><%= link_to 'Show', reg %></td>
        <td><%= link_to 'Edit', edit_reg_path(reg) %></td>
        <td><%= link_to 'Destroy', reg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reg', new_reg_path %>

app/views/regs/new.html.erb
<%= javascript_include_tag 'reg' %>
<div class ="main" style="width:20; float:left" >
<br>
<br>

<%= image_tag("download.jpg", :alt => "rss feed", :size => "550x600", :class =>"mySlides") %>
 

</div>
 <div class ="container" style="width:10; float:right">
<h1>Register Here</h1>
<br>
<%= form_for @reg, url:{action: "create"} do |f| %>
<p>
<%= f.label :Username %>
<%= f.text_field :username %>
</p>
<p>
<%= f.label :Password %>
<%= f.password_field  :password %>
</p>
<p>
<%= f.label :Date_Of_Birth %>
<%= f.date_select  :dateofbirth %>
</p>
<p>
<%= f.label :Email %>
<%= f.text_field  :email %>
</p>
<p>
<%= f.label :Telephone %>
<%= f.text_field  :telephone %>
</p>
<p>
<%= f.label :Address %>
<%= f.text_area  :address, :maxlength => "254px" %>
</p>
<p>
<%= f.label :City %>
<%= f.text_field  :city %>
</p>
<p>
<%= f.label :Postal_Code %>
<%= f.text_field  :postcode %>
</p>


<p>
<%= f.submit("create") %>
</p>
<p>Note: Please make sure your details are correct before<br/>
 submitting form and that all fields marked with * are completed!.</p>
</div>
<% end %>

app/views/regs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @reg.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @reg.password %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @reg.dateofbirth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @reg.email %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @reg.telephone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @reg.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @reg.city %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @reg.postcode %>
</p>

<%= link_to 'Edit', edit_reg_path(@reg) %> |
<%= link_to 'Back', regs_path %>